export default class MediaItemSource extends String {
	static Billboard = "billboard";
	static Complex = "complex-music";
	static Highsnobiety = "highsnobiety";
	static EliteDaily = "elitedaily";
	static Fader = "fader";
	static FactMag = "factmag";
	static FourPins = "fourpins";
	static Genius = "genius";
	static HotNewHipHop = "hnhh";
	static Hypebeast = "hypebeast";
	static MTV = "mtv-news";
	static Paper = "paper";
	static PigeonsAndPlanes = "pigeonsandplanes";
	static Spotify = "spotify";
	static SpinMusic = "spin-music";
	static SpinNews = "spin-news";
	static Soundcloud = "soundcloud";
	static Youtube = "youtube";
	static VibeNews = "vibe-news";
	static VibeMusic = "vibe-music";
	static Vice = "vice";
	static XXLMag = "xxlmag";
	static TMZ = "tmz";
	static Unknown = "unknown";
};
